name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      example_list:
        description: 'Example list input'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest   


#     steps:
#       - name: Parse list input
#         run: |
#           list_input="${{ fromJson(inputs.example_list) }}"
#           echo "The list input is: $list_input"
#       - name: Iterate over the list
#         run: |
#           for item in $list_input; do
#             echo $item
#           done


    steps:
      - name: Split list input
        id: split_input
        run: |
          list_input="${{ inputs.example_list }}"
          IFS=',' read -ra arr <<< "$list_input"
          echo  split_list=${arr[*] >> $GITHUB_OUTPUT
          
      - name: Use split list
        run: |
          echo "The split list is: ${{ steps.split_input.outputs.split_list }}"
          for val in ${{ steps.split_input.outputs.split_list }}; do
            echo $val
          done
