name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      example_list:
        description: 'Example list input'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest   


    steps:
      - name: Parse list input
        run: |
          list_input="${{ fromJson(inputs.example_list) }}"
          echo "The list input is: $list_input"
      - name: Iterate over the list
        run: |
          for item in $list_input; do
            echo $item
          done
