name: Dump Users (manual)

on:
  workflow_dispatch:
    inputs:
      sesas:
        type: string
        required: true

jobs:
  dump_users_information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump Users
        shell: bash
        run: |
          echo "${{ github.event.inputs.sesas }}"
          for value in "${{ github.event.inputs.sesas }}"
          do
            echo $value
          done
