name: Dump Users (manual)

on:
  workflow_dispatch:
    inputs:
      sesas:
        type: string
        required: true

jobs:
  dump_users_information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse list input
        run: |
          list_input="${{ fromJson(inputs.sesa) }}"
          echo "The list input is: $list_input"
